<!doctype html>
<html>
<head>
<meta charset="utf-8">
<title>Try and Catch</title>
</head>

<body>

    <script>
    //    try{
    //         add(2,3);
    //    }
    //    catch(e){    // This block will execute when there is an error
    //     console.log("The error Message is " + e.message);
    //     console.log("The error Description is " + e.description);
    //     console.log("The error stack is " +e.stack);
    //    }
    //    finally      // The finally block is guaranteed to execute
    //    {
    //        console.log("This block will execute"); 
    //    }






// function Sub(a,b)
// {
//     return a-b;
// }

// try
// {
//     console.log(Sub(21,4));

// }
// catch   // This block will not execute
// {
//         console.log("The error Message is " + e.message);
//         console.log("The error Description is " + e.description);
//         console.log("The error stack is " +e.stack);

// }



// Customized execption
// var numerator=Number(prompt("Enter the Numerator"));
// var denominator=Number(prompt("Enter the Denominator"));

// try{
// if(denominator==0)
// {
//     throw{
//         error: "Divide by 0 error",
//         message: "Divide by 0 is not possible"
//     }
// }
// else{
//     document.write("The answer is " + numerator/denominator);
// }
// }
// catch(e)
// {
// document.write("The Error is " +e.error +"<br>");
// document.write("The Error Description is " +e.message);

// }









    </script>
</body>
</html>
